import { ArrowRight, Check } from "lucide-react";
import { Link } from "react-router";
import { PublicPageMeta } from "@/components/public/public-page-meta";

type ContentPageProps = { eyebrow: string; title: string; intro: string; sections: Array<{ title: string; copy: string }> };

export function ContentPage({ eyebrow, title, intro, sections }: ContentPageProps) {
  return <>
    <PublicPageMeta title={eyebrow} description={intro} />
    <section className="public-page-hero"><p className="public-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="public-lede">{intro}</p></section>
    <section className="public-editorial-list">{sections.map((section, index) => <article key={section.title}><span>0{index + 1}</span><div><h2>{section.title}</h2><p>{section.copy}</p></div></article>)}</section>
    <section className="public-content-note"><Check aria-hidden="true" /><div><h2>Content approval needed</h2><p>This structure is ready for verified school details, approved policies, original photography and current information. Nothing shown here claims facts not yet supplied by the school.</p></div></section>
    <section className="public-admissions-cta"><p className="public-eyebrow">Next step</p><h2>Let’s make the information useful.</h2><Link className="public-primary-button" to="/contact">Contact the school <ArrowRight aria-hidden="true" /></Link></section>
  </>;
}

export const pages = {
  about: { eyebrow: "About", title: "A school defined by the people and purpose behind it.", intro: "Mission, values, history, leadership and the reasons families choose the school belong here—after they have been verified and approved.", sections: [{ title: "Our school", copy: "A concise introduction to the school’s identity, setting and educational promise." }, { title: "Mission, vision and values", copy: "A human explanation of the principles that guide teaching, care and community." }, { title: "Leadership and trust", copy: "Approved leadership profiles, governance information and school policies." }] },
  academics: { eyebrow: "Academics", title: "Learning designed for each stage of a child’s growth.", intro: "Clear pathways for Nursery, Kindergarten, Standard I–VII and Form I–IV will replace one-size-fits-all course listings.", sections: [{ title: "Nursery & Kindergarten", copy: "Playful, caring early learning content, routines and family partnership." }, { title: "Primary: Standard I–VII", copy: "A structured primary curriculum, subjects, learning support and progression." }, { title: "Secondary: Form I–IV", copy: "Subjects, examination preparation, guidance and appropriate results reporting." }, { title: "Academic calendar", copy: "Approved term dates, examination periods and school-year milestones." }] },
  admissions: { eyebrow: "Admissions", title: "A calm, transparent path from first question to enrolment.", intro: "Families should be able to understand requirements, plan a visit and begin an application without navigating a maze of pages.", sections: [{ title: "1. Discover", copy: "Explore programmes and ask an initial question." }, { title: "2. Visit", copy: "Arrange an approved school visit or virtual conversation." }, { title: "3. Apply", copy: "Submit a secure application with clearly stated requirements." }, { title: "4. Join", copy: "Receive next steps and verified enrolment communication." }] },
  schoolLife: { eyebrow: "School life", title: "The experiences around learning are part of learning.", intro: "School Life will centre real student participation—clubs, sport, arts, trips, facilities, wellbeing and safeguarding.", sections: [{ title: "Create and contribute", copy: "Student leadership, clubs, arts and service stories." }, { title: "Move and belong", copy: "Sports, health, teams and inclusive participation." }, { title: "Explore safely", copy: "Trips, facilities, safeguarding and wellbeing information." }] },
  newsEvents: { eyebrow: "News & events", title: "A useful public window into school life.", intro: "Public editorial stories and events belong here; private academic notices and personal communications belong in the portal.", sections: [{ title: "News", copy: "Approved school stories with dates, authors and original photography." }, { title: "Events", copy: "A filterable public calendar with accessible date and location details." }, { title: "Announcements", copy: "School-wide notices suitable for public publication." }] },
  community: { eyebrow: "Community", title: "A shared school experience, with distinct needs for each audience.", intro: "Students, parents, teachers and staff need clear public guidance and a secure route into the portal.", sections: [{ title: "Students", copy: "Opportunities, support and secure access to personal learning information." }, { title: "Parents", copy: "Practical school information and a child-centred secure portal experience." }, { title: "Teachers & staff", copy: "Professional community information and staff systems." }] },
  contact: { eyebrow: "Contact", title: "Connect with the school.", intro: "Approved phone numbers, email addresses, physical location, visiting hours and enquiry options will appear here after they are supplied.", sections: [{ title: "Admissions enquiries", copy: "A verified contact route and response commitment." }, { title: "Visit the school", copy: "Approved campus location, directions and visit booking." }, { title: "General contact", copy: "A secure, accessible enquiry form with clear privacy information." }] },
};
