import { ArrowRight, Check } from "lucide-react";
import { Link } from "react-router";
import { PublicPageMeta } from "@/components/public/public-page-meta";

type ContentPageProps = { eyebrow: string; title: string; intro: string; sections: Array<{ title: string; copy: string }> };

export function ContentPage({ eyebrow, title, intro, sections }: ContentPageProps) {
  const heroImage = eyebrow === "Community" ? "/images/kijani-community-voice.png" : "/images/kijani-hero.png";
  return <>
    <PublicPageMeta title={eyebrow} description={intro} />
    <section className="public-page-hero public-content-hero"><div><p className="public-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="public-lede">{intro}</p></div><div className="public-content-hero-media"><img src={heroImage} alt="" /></div></section>
    <section className="public-editorial-list" aria-label={`${eyebrow} information`}><div className="public-editorial-list-label"><p className="public-eyebrow">At a glance</p><p>What families and the wider community should know.</p></div>{sections.map((section, index) => <article key={section.title}><span aria-hidden="true">0{index + 1}</span><div><h2>{section.title}</h2><p>{section.copy}</p></div></article>)}</section>
    <section className="public-content-note"><Check aria-hidden="true" /><div><h2>Demo profile ready to edit</h2><p>This page uses representative Kijani content to show the intended structure. Replace it with approved school facts, policies, people, dates and original media before launch.</p></div></section>
    <section className="public-admissions-cta"><p className="public-eyebrow">Next step</p><h2>Find the right route for your family.</h2><Link className="public-primary-button" to="/contact">Contact the school <ArrowRight aria-hidden="true" /></Link></section>
  </>;
}

export const pages = {
  about: { eyebrow: "About", title: "A school defined by purpose, curiosity and belonging.", intro: "Kijani International School is a demo profile for a welcoming learning community in Dar es Salaam, designed around strong foundations and global-minded thinking.", sections: [{ title: "Our school", copy: "Kijani brings Nursery, Primary and Secondary learners together in a community where every child is known, challenged and encouraged to contribute." }, { title: "Mission, vision and values", copy: "Our mission is to help young people learn with purpose. We value curiosity, kindness, integrity, courage and responsibility for the wider community." }, { title: "Leadership and trust", copy: "Teachers, families and school leaders work together through clear communication, thoughtful safeguarding and a shared commitment to each learner’s growth." }] },
  academics: { eyebrow: "Academics", title: "Learning designed for each stage of a child’s growth.", intro: "Clear pathways for Nursery, Kindergarten, Standard I-VII and Form I-IV replace one-size-fits-all course listings.", sections: [{ title: "Nursery & Kindergarten", copy: "Playful, caring early learning builds language, early numeracy, movement, creativity and confident relationships." }, { title: "Primary: Standard I-VII", copy: "A broad curriculum connects literacy, mathematics, science, languages, social studies, arts, sport and digital learning." }, { title: "Secondary: Form I-IV", copy: "Students deepen subject knowledge, develop independent study habits and prepare thoughtfully for their next step." }, { title: "Academic rhythm", copy: "Each term balances focused learning, review, projects, enrichment and family conversations about progress." }] },
  admissions: { eyebrow: "Admissions", title: "A calm, transparent path from first question to enrolment.", intro: "Families can understand the journey, plan a conversation and begin an enquiry without navigating a maze of pages.", sections: [{ title: "1. Discover", copy: "Explore the learning stages and send a focused question to the admissions team." }, { title: "2. Visit", copy: "Arrange a campus visit or virtual conversation to understand the community and daily experience." }, { title: "3. Apply", copy: "Receive current entry requirements and submit the approved application information securely." }, { title: "4. Join", copy: "Follow clear next steps for enrolment, orientation and a confident start to school life." }] },
  schoolLife: { eyebrow: "School life", title: "The experiences around learning are part of learning.", intro: "Students grow through participation, creativity, sport, service, friendships and the everyday care of a connected school community.", sections: [{ title: "Create and contribute", copy: "Arts, clubs, projects, student leadership and service give learners meaningful ways to make and share." }, { title: "Move and belong", copy: "Sports, outdoor activity and teamwork support healthy habits, confidence and inclusive participation." }, { title: "Explore safely", copy: "Trips, facilities, wellbeing support and safeguarding help students explore with curiosity and care." }] },
  newsEvents: { eyebrow: "News & events", title: "A useful public window into school life.", intro: "Public stories and events belong here; private academic notices and personal communications remain in the secure portal.", sections: [{ title: "News", copy: "Share approved school stories with dates, clear authorship and original photography." }, { title: "Events", copy: "Publish public dates with accessible details for families, visitors and the wider community." }, { title: "Announcements", copy: "Keep school-wide notices concise, relevant and appropriate for public publication." }] },
  community: { eyebrow: "Community", title: "One school experience, with a clear route for every audience.", intro: "Students, parents, teachers and staff each need useful public guidance and a secure route into the right school tools.", sections: [{ title: "Students", copy: "Find opportunities, support and secure access to personal learning information." }, { title: "Parents", copy: "Get practical school information and a child-centred portal experience for everyday partnership." }, { title: "Teachers & staff", copy: "Access professional information, operational workflows and the systems that support teaching." }] },
  contact: { eyebrow: "Contact", title: "Connect with Kijani.", intro: "Start with admissions, a visit question or a general message. The demo profile includes editable school contact routes.", sections: [{ title: "Admissions enquiries", copy: "Ask about Nursery, Primary or Secondary and receive a clear response from the admissions team." }, { title: "Visit the school", copy: "Use the contact page to find the demo campus address, opening hours and visit conversation route." }, { title: "General contact", copy: "Send a concise enquiry while keeping sensitive child, health, payment and account information private." }] },
};
