import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Link, useParams } from "react-router";
import { PublicPageMeta } from "@/components/public/public-page-meta";
import PublicNotFoundPage from "@/pages/public/not-found";

type Detail = { eyebrow: string; title: string; intro: string; sections: Array<{ title: string; copy: string }>; image: string; back: string };

const detail = (eyebrow: string, title: string, intro: string, sections: Detail["sections"], back: string, image = "/images/kijani-hero.png"): Detail => ({ eyebrow, title, intro, sections, back, image });

const DETAILS: Record<string, Detail> = {
  "our-story": detail("About / Our story", "A school built around the whole journey.", "Discover the story, people and shared purpose behind a connected Nursery, Primary and Secondary education.", [{ title: "A connected beginning", copy: "Children are known well from their first questions through the choices they make as they grow." }, { title: "Learning with purpose", copy: "Strong foundations, practical experiences and thoughtful relationships help learners understand why their work matters." }, { title: "A community that participates", copy: "Families, teachers and students each contribute to a culture of curiosity, kindness and responsibility." }], "/about"),
  "mission-values": detail("About / Mission and values", "Purpose is something we practise every day.", "Our mission and values make the school’s decisions visible: in classrooms, conversations, care and community life.", [{ title: "Curiosity", copy: "We ask better questions, listen carefully and make room for new ideas." }, { title: "Kindness and integrity", copy: "We treat people with respect and take responsibility for our choices." }, { title: "Courage to contribute", copy: "We encourage learners to try, improve, lead and help others." }], "/about"),
  leadership: detail("About / Leadership", "Leadership that keeps children at the centre.", "Meet the principles that guide school leadership, teaching teams and family partnership.", [{ title: "Clear direction", copy: "Leaders set a focused direction while giving teachers the trust to respond to learners." }, { title: "Shared responsibility", copy: "Safeguarding, wellbeing and progress belong to the whole school community." }, { title: "Open communication", copy: "Families should know where to ask questions and how decisions are made." }], "/about"),
  "campus-facilities": detail("About / Campus and facilities", "Spaces designed for active learning.", "Explore the places where reading, making, movement, collaboration and quiet focus become part of the school day.", [{ title: "Flexible classrooms", copy: "Rooms support discussion, independent work, practical projects and different ways of learning." }, { title: "Specialist spaces", copy: "Library, science, creative and digital learning spaces help students turn ideas into experience." }, { title: "Outdoor life", copy: "Outdoor areas create space for movement, play, sport and community gatherings." }], "/school-life"),
  safeguarding: detail("About / Safeguarding", "Safety is the foundation for belonging.", "Our safeguarding approach is built around trusted adults, clear responsibilities and a culture where concerns are heard.", [{ title: "A shared duty", copy: "Every adult has a responsibility to notice, respond and report concerns through the right route." }, { title: "Respectful relationships", copy: "Students learn in an environment that protects dignity, inclusion and wellbeing." }, { title: "Approved information", copy: "Policies and contacts should be replaced with the school’s current, approved safeguarding details before launch." }], "/community"),
  "early-years": detail("Learning / Early Years", "Begin with wonder.", "Nursery and Kindergarten give children time, care and confidence to explore the world around them.", [{ title: "Play with purpose", copy: "Play-based experiences develop language, early numeracy, movement and creative expression." }, { title: "Warm relationships", copy: "Teachers build secure routines and know each child’s interests, strengths and next steps." }, { title: "A confident start", copy: "Families receive clear guidance as children begin their learning journey." }], "/academics", "/images/kijani-community-voice.png"),
  primary: detail("Learning / Primary School", "Build strong foundations.", "Primary learning connects knowledge, creativity and practical problem-solving from Standard I to VII.", [{ title: "Broad and balanced", copy: "Literacy, mathematics, science, languages, social studies, arts, sport and digital learning work together." }, { title: "Growing independence", copy: "Students learn to organise ideas, explain their thinking and take increasing ownership." }, { title: "Progress made visible", copy: "Teachers use classroom evidence and age-appropriate assessment to guide support." }], "/academics", "/images/kijani-creative-learning.png"),
  secondary: detail("Learning / Secondary School", "Find your direction.", "Form I to IV brings challenge, responsibility and the confidence to make thoughtful choices.", [{ title: "Deeper subject knowledge", copy: "Students build the habits and understanding needed for examinations and future pathways." }, { title: "Independent study", copy: "Learners practise planning, research, revision and reflection with support from teachers." }, { title: "Ready for what follows", copy: "The school helps students connect their strengths to academic, vocational and community opportunities." }], "/academics", "/images/kijani-hero.png"),
  curriculum: detail("Learning / Curriculum", "A curriculum with room to think.", "See how subjects connect strong foundations with inquiry, communication, creativity and practical problem-solving.", [{ title: "Knowledge that connects", copy: "Students see relationships between subjects and apply ideas beyond a single lesson." }, { title: "Skills for a changing world", copy: "Communication, collaboration, digital confidence and critical thinking are developed deliberately." }, { title: "Support at every stage", copy: "Teachers adapt explanation, practice and challenge to help each learner progress." }], "/academics"),
  "learning-support": detail("Learning / Learning support", "The right challenge for every learner.", "Learning support works with students, teachers and families to remove barriers and build confidence.", [{ title: "Early understanding", copy: "Teachers use observation and classroom evidence to notice strengths and needs early." }, { title: "Practical strategies", copy: "Clear routines, targeted practice and accessible explanations help students participate fully." }, { title: "Partnership with families", copy: "Progress is discussed respectfully with families through appropriate school channels." }], "/academics"),
  examinations: detail("Learning / Examinations", "Preparation with perspective.", "Examinations matter, but they are one part of a wider education built on understanding and steady habits.", [{ title: "Know the pathway", copy: "Families receive current, verified information about subjects, dates and entry requirements." }, { title: "Build good habits", copy: "Planning, revision, feedback and wellbeing support help students prepare sustainably." }, { title: "Look beyond results", copy: "Teachers help students connect achievement to their next academic or vocational step." }], "/academics"),
  "why-choose-us": detail("Admissions / Why choose us", "A school where children are known.", "Choosing a school starts with the experience you want your child to have every day.", [{ title: "One connected journey", copy: "Nursery, Primary and Secondary stages share a common purpose while respecting each age and stage." }, { title: "Learning and character", copy: "Academic foundations sit alongside curiosity, kindness, confidence and contribution." }, { title: "A welcoming conversation", copy: "Our admissions team helps families ask the right questions before deciding." }], "/admissions", "/images/kijani-community-voice.png"),
  journey: detail("Admissions / The admissions journey", "A clear path from question to enrolment.", "Understand the steps, conversations and decisions that help a family find the right route.", [{ title: "Discover", copy: "Explore the stages of learning and send a focused enquiry." }, { title: "Visit", copy: "Meet the school, ask questions and experience the campus or an approved virtual conversation." }, { title: "Apply and join", copy: "Receive current requirements, submit approved information and prepare for a confident start." }], "/admissions"),
  requirements: detail("Admissions / Entry requirements", "Current information, clearly explained.", "Entry requirements should be easy to find, accurate and confirmed directly by the school.", [{ title: "Age and stage", copy: "Requirements vary by Nursery, Primary and Secondary entry point." }, { title: "Documents and assessments", copy: "The admissions team confirms only the documents and assessments needed for your stage." }, { title: "Ask before submitting", copy: "Contact the school if your child’s circumstances or pathway need a conversation." }], "/admissions"),
  visit: detail("Admissions / Book a visit", "See the school in real life.", "A visit gives families the clearest sense of relationships, routines, spaces and learning.", [{ title: "Plan your conversation", copy: "Tell the school what you would like to understand so the visit is useful to your family." }, { title: "Meet the community", copy: "Where appropriate, visits include time with school leaders, teachers and students." }, { title: "Take the next step", copy: "After a visit, the admissions team can explain requirements and timing." }], "/contact", "/images/kijani-hero.png"),
  "request-information": detail("Admissions / Request information", "Start with the information you need.", "Ask a focused question and receive a clear response without sharing sensitive personal documents.", [{ title: "Keep it focused", copy: "Tell us the stage you are considering and what you would like to know." }, { title: "Privacy by design", copy: "Do not include identity documents, health information, payment details or portal passwords." }, { title: "A timely reply", copy: "The school uses your contact details only to respond to the enquiry." }], "/admissions"),
  faqs: detail("Admissions / FAQs", "Answers before your first conversation.", "Find practical guidance about visits, requirements, stages and what happens after an enquiry.", [{ title: "What happens after I enquire?", copy: "The admissions team reviews your question and replies using the contact details you provide." }, { title: "Can I visit the school?", copy: "Visit availability and arrangements are confirmed directly by the school." }, { title: "Where are requirements listed?", copy: "The school provides current, verified entry requirements for the stage you select." }], "/admissions"),
  "student-life": detail("School life / Student life", "A school day made of many moments.", "Friendship, responsibility, creativity and participation shape the experience around lessons.", [{ title: "Find your place", copy: "Students discover interests and build relationships through shared experiences." }, { title: "Take responsibility", copy: "Age-appropriate leadership and contribution help students grow in confidence." }, { title: "Be supported", copy: "Trusted adults and clear routines make it easier to ask for help." }], "/school-life", "/images/kijani-community-voice.png"),
  "sports-wellbeing": detail("School life / Sports and wellbeing", "Move, play and feel well.", "Sport and wellbeing support healthy habits, teamwork and confident participation.", [{ title: "Everyone can take part", copy: "Activities are designed to build enjoyment, skill and belonging at every stage." }, { title: "Healthy routines", copy: "Movement, rest, relationships and reflection all contribute to wellbeing." }, { title: "Teamwork in action", copy: "Students learn to encourage one another, handle challenge and celebrate progress." }], "/school-life"),
  "arts-music": detail("School life / Arts and music", "Find a voice through making.", "Music, visual arts, drama and creative work give students space to experiment and share.", [{ title: "Make and explore", copy: "Students practise ideas, materials and techniques without fear of getting it wrong." }, { title: "Perform and communicate", copy: "Creative work helps learners express meaning and listen to different perspectives." }, { title: "Celebrate process", copy: "Progress is valued alongside finished performances, exhibitions and pieces." }], "/school-life", "/images/kijani-creative-learning.png"),
  "clubs-activities": detail("School life / Clubs and activities", "Learning beyond the timetable.", "Clubs and activities help students follow interests, meet others and build new skills.", [{ title: "Try something new", copy: "A varied programme gives learners a chance to discover interests they did not expect." }, { title: "Learn with others", copy: "Clubs build collaboration, communication and a sense of shared purpose." }, { title: "Lead and contribute", copy: "Older students can help shape activities and welcome younger learners." }], "/school-life"),
  "trips-service": detail("School life / Trips and service", "Open the door to the wider community.", "Trips, projects and service connect learning to real places, people and responsibilities.", [{ title: "Prepare thoughtfully", copy: "Students understand purpose, expectations and safety before an experience begins." }, { title: "Learn from place", copy: "Visits make subjects tangible and encourage observation, questions and reflection." }, { title: "Give back", copy: "Service helps learners notice needs and make a meaningful contribution." }], "/school-life"),
  facilities: detail("School life / Our facilities", "Spaces that make learning visible.", "Explore the flexible classrooms, specialist areas and outdoor spaces that support a complete school experience.", [{ title: "Flexible classrooms", copy: "Rooms support discussion, independent work and practical projects." }, { title: "Specialist learning", copy: "Library, science, creative and digital spaces give ideas room to become real." }, { title: "Outdoor spaces", copy: "Play, sport and quiet outdoor time are part of a balanced day." }], "/school-life", "/images/kijani-hero.png"),
  students: detail("Community / Students", "A clear route for every learner.", "Students need public guidance about opportunities and a secure route for personal learning information.", [{ title: "Discover opportunities", copy: "Explore learning, activities, support and ways to contribute to school life." }, { title: "Protect personal information", copy: "Grades, attendance and individual communication belong in the secure portal." }, { title: "Ask for support", copy: "Trusted adults can help students find the right academic or wellbeing route." }], "/community"),
  families: detail("Community / Families", "Partnership that helps children thrive.", "Families are part of the learning community, with clear public information and secure everyday tools.", [{ title: "Stay informed", copy: "Public news, events and approved school information are available without an account." }, { title: "Work together", copy: "Questions about progress, wellbeing or routines are best handled through the appropriate school channel." }, { title: "Use the portal", copy: "Personal records and family communication stay protected behind the secure portal." }], "/community"),
  staff: detail("Community / Teachers and staff", "The people who make learning possible.", "Teaching and support teams combine professional knowledge with care, consistency and collaboration.", [{ title: "Teach with purpose", copy: "Staff use evidence, relationships and reflection to help learners progress." }, { title: "Work as a team", copy: "Clear systems make it easier to share responsibility and support students." }, { title: "Protect trust", copy: "Safeguarding, privacy and professional conduct guide every interaction." }], "/community"),
  alumni: detail("Community / Alumni", "A connection that continues beyond school.", "Alumni stories and relationships show how a school community continues to grow over time.", [{ title: "Stay connected", copy: "Share milestones, opportunities and memories through approved school channels." }, { title: "Give back", copy: "Alumni can inspire current students through conversations, mentoring and service." }, { title: "Tell your story", copy: "The school welcomes approved stories that reflect diverse journeys." }], "/community", "/images/kijani-community-voice.png"),
  "resources-policies": detail("Community / Resources and policies", "Useful information, in the right place.", "Families and visitors should be able to find approved policies, contacts and practical resources without confusion.", [{ title: "Clear and current", copy: "Published resources should carry an owner, review date and accessible format." }, { title: "Safeguarding first", copy: "Child protection and urgent contact routes must be prominent and easy to use." }, { title: "Private where needed", copy: "Personal records and internal operational documents belong in the secure portal." }], "/community"),
  latest: detail("News & events / Latest news", "Stories from school life.", "Approved school news should be timely, accessible and grounded in the real work of the community.", [{ title: "Lead with the story", copy: "Use a clear headline, date, context and original image or caption where appropriate." }, { title: "Celebrate thoughtfully", copy: "Share achievement while respecting consent, privacy and safeguarding." }, { title: "Keep families connected", copy: "Link public stories to the right next step without exposing private information." }], "/news-events", "/images/kijani-creative-learning.png"),
  calendar: detail("News & events / Events calendar", "Know what is coming up.", "A public calendar helps visitors and families understand the rhythm of school life.", [{ title: "Useful dates", copy: "Show event title, date, time and audience in a consistent, scannable format." }, { title: "Accessible details", copy: "Descriptions should explain what visitors need to know without unnecessary jargon." }, { title: "Keep it current", copy: "Remove cancelled or outdated events and show the latest approved information." }], "/news-events"),
  announcements: detail("News & events / Announcements", "The right message for the right audience.", "Public announcements should be concise, relevant and approved for wider publication.", [{ title: "Be clear", copy: "Lead with the action, date or decision that readers need to understand." }, { title: "Protect privacy", copy: "Personal, academic and class communications stay within the secure portal." }, { title: "Make it findable", copy: "Use consistent headings and dates so important notices are easy to scan." }], "/news-events"),
};

export default function PublicDetailPage() {
  const { slug = "" } = useParams();
  const page = DETAILS[slug];
  if (!page) return <PublicNotFoundPage />;
  return <><PublicPageMeta title={page.eyebrow} description={page.intro} /><section className="public-page-hero public-detail-hero"><div><p className="public-eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p className="public-lede">{page.intro}</p></div><div className="public-detail-image"><img src={page.image} alt="" fetchPriority="high" decoding="async" /></div></section><section className="public-detail-content"><div className="public-detail-heading"><p className="public-eyebrow">In focus</p><h2>What families should know</h2></div><div className="public-detail-grid">{page.sections.map((section, index) => <article key={section.title}><span className="public-detail-number">0{index + 1}</span><h3>{section.title}</h3><p>{section.copy}</p><CheckCircle2 aria-hidden="true" /></article>)}</div><Link className="public-detail-back" to={page.back}><ArrowRight className="h-4 w-4 rotate-180" aria-hidden="true" /> Back to {page.back === "/" ? "home" : page.back.replace("/", "").replaceAll("-", " ")}</Link></section></>;
}
