import { ArrowRight, Compass, HeartHandshake, Palette, Trophy } from "lucide-react";
import { Link } from "react-router";
import { PublicPageMeta } from "@/components/public/public-page-meta";

const areas = [
  { icon: Trophy, title: "Sport & movement", copy: "Games, movement and outdoor activity help students build teamwork, healthy habits and confidence at every age." },
  { icon: Palette, title: "Arts & expression", copy: "Music, visual arts, drama and making give students space to experiment, perform and find their voice." },
  { icon: Compass, title: "Clubs, trips & leadership", copy: "Clubs, projects, local trips and student leadership extend learning beyond the classroom and into the community." },
  { icon: HeartHandshake, title: "Care, safety & belonging", copy: "A welcoming school culture is built through trusted adults, respectful relationships, wellbeing support and clear safeguarding practice." },
];

export default function SchoolLifePage() {
  return <><PublicPageMeta title="School Life" description="Explore Eckernforde Schools activities, facilities and student support." /><section className="public-page-hero"><p className="public-eyebrow">School life</p><h1>Learning continues in every place a child participates, creates and belongs.</h1><p className="public-lede">School life should show the full experience around learning without exaggeration: real opportunities, real care and real community.</p></section><section className="mx-auto max-w-[1440px] px-4 pb-20 sm:px-6 lg:px-10"><div className="grid border-t border-[#172b3a]/20 md:grid-cols-2">{areas.map((area, index) => { const Icon = area.icon; return <article key={area.title} className={`min-h-64 border-b border-[#172b3a]/20 p-6 sm:p-9 ${index % 2 === 0 ? "md:border-r" : ""}`}><Icon className="h-7 w-7 text-[#ba4a32]" aria-hidden="true" /><p className="mt-10 text-xs font-bold uppercase tracking-[.15em] text-[#172b3a]/55">School life</p><h2 className="mt-3 font-serif text-3xl leading-tight">{area.title}</h2><p className="mt-4 max-w-md text-sm leading-7 text-[#172b3a]/75">{area.copy}</p></article>; })}</div><div className="mt-16 grid gap-8 lg:grid-cols-[1fr_.8fr]"><div className="border-l-4 border-[#ba4a32] pl-6"><p className="public-eyebrow">Facilities & resources</p><h2 className="mt-3 font-serif text-4xl leading-tight">Spaces that make learning visible.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-[#172b3a]/75">The Eckernforde Schools campus story brings together flexible classrooms, a library and reading spaces, science learning, creative studios, ICT access and outdoor areas for play and sport.</p></div><div className="border border-[#172b3a]/15 bg-white p-7"><p className="public-eyebrow">Current families</p><h2 className="mt-3 font-serif text-2xl">Daily updates stay private.</h2><p className="mt-3 text-sm leading-6 text-[#172b3a]/75">Personal announcements, homework, attendance and calendars are available only through the secure portal.</p><Link className="public-text-link mt-6" to="/portal">Open secure portal <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div></div></section></>;
}
